language: generic
dist: xenial

branches:
  only:
    - master

before_install:
  - sudo apt-get install git
  - chmod +x ./CI/push.sh

script:
  - node ./CI/build.js $TRAVIS_COMMIT_MESSAGE

after_success:
  - ./CI/push.sh
